### ISSUE TITLE
Writing statistics do not agree with other online solutions

### ISSUE THREAD

**Issue by keeferrourke** [ian-james/IFS#94] opened 2017-07-19 06:28 UTC
### Description
For the most recent CIS\*2520 assignment, I uploaded some of my documentation to the IFS to check for grammar and spelling errors; the word count according to IFS is as follows:

> Character Count: 13245
> Words Count: 2681

According to [wordcounter.net](http://wordcounter.net), for the same file, those same statistics are as follows:

> 2,941 words 19,672 characters

### Expected behaviour
These statistics should agree with one another.

### Actual behaviour
The IFS counts seem to be much lower than they should be.

### Steps to reproduce
 1. Log into IFS.
 2. Select Writing Tools under Preferences.
 3. Enable Writing Statistics.
 4. Upload a file.
 5. Upload the same file to a different word counting service.
 6. Observe the difference in the reported statistics.

#### IFS Version
v0.0.1

#### Browser
Please tick the affected browsers.

 - [x] Chrome/Chromium-based
 - [x] Firefox
 - [ ] Safari
 - [ ] Internet Explorer 11
 - [ ] Microsoft Edge
 - [ ] Other (Please write below)

**Comment by ian-james** [comment] 2017-07-19 15:35
There won't be much we can do about this but change programs that is run since there isn't any calculations here. We should confirm against another 3rd and 4th application which answer is "correct" or most consistent.

**Comment by ian-james** [comment] 2017-07-23 02:20
Identified two bugs with Style the program behind the statistics:
1) The last line of text is not processed if  the last sentence isn't punctuated. This is actually a really common error in NLP parsing. Lots of parsing tools have this issue as I've been caught by this in python and javascript parsers. Not sure if this applies to end of paragraphs, it doesn't seem to from my quick tests.

2) I'm  and other apostrophes are treated as multiple worlds which doesn't appear to be the cause in wc and other tools.

While this is a really good error catch. I'm closing this since it's a very specific error that causes it the miscount (AFAIK) and there isn't anything we can do about it either way.

**Closed by ian-james** 2017-07-23 02:20 UTC
Labels: investigate

**Comment by keeferrourke** [comment] 2017-07-23 17:18
@ian-james can we make a separate call to `wc` to fix the word counts if the NLTK can't parse words correctly? `wc` should be available on every Unix, and has other options for line counts, etc.

**Comment by ian-james** [comment] 2017-07-23 20:44
It's likely not worth the effort, NLTK does parse correctly in other cases.
