### ISSUE TITLE
IFS->Tool Page->Tool Selection

### ISSUE THREAD

**Issue by ian-james** [ian-james/IFS#145] opened 2018-07-05 03:27 UTC
The enable/disable clicking easily gets out of sync with 1 or 2 presses.

Visual will show tool is disable but dropdown will be visible and vice-versa.

**Comment by ian-james** [comment] 2018-07-09 02:28
Adding Rhys to do a peer review of these features. Notice a couple issues but didn't have time to document before leaving.

**Comment by ryoung2512** [comment] 2018-07-09 14:17
The enable disable of a tool seems to work fine for me. However, switching between programming and writing does not.

What I tried:
1. Regular clicking of the toggle button - **passed**
2. Spam clicking of the toggle button - **passed**
3. Changing contents of div inside and toggling - **passed**
4. Toggling tool settings visibility, then toggling the visual - **passed**
5. Tried switching between programming and writing then enabling/disabling - **failed**

To reproduce the error I found:
1. Go into preferences, set preferred assessment tool to writing.
2. When on tool selection page, change from writing to programming.
3. You can now no longer choose writing anymore, it will just keep displaying programming. Also, neither button is highlighted anymore.

Try switching it to a [uikit switcher](https://getuikit.com/docs/switcher). It will be a lot more responsive that way as well.

Let me know if you have any questions!

**Comment by kglovern** [comment] 2018-07-09 15:34
I have the same issue as Rhys with switching between programming and writing tools on the new interface.  The bug is due to the incorrect value being stored as "pref-toolSelect" option.

To reproduce:
1) Visit "/preferences" and select writing or programming
2) In MySQL client, "select * from preferences where toolName="pref-toolSelect"; shows the correct value of 'programming' or 'writing'
3) Now use the tool option on the "/tool" route to try to swap between the two - user is stuck on programming as stated above
4) "select * from preferences where toolName="pref-toolSelect"; value is now the html source of the page instead of a value of either "writing" or "programming"

Check what is being passed as the toolSelect value - the HTML server response is being stored as the value instead of the actual toolSelect value.

**Comment by ndomenic** [comment] 2018-07-09 21:55
I am unable to reproduce this error using both of the aforementioned steps. It never sticks for me, and the database is always updated. I am testing this on the latest version of the development branch.

**Comment by ian-james** [comment] 2018-07-09 22:50
Ok, well then we could close this bug. I'll double check when I get back.
But open one for the other issue and and assign to whoever is free

**Comment by ian-james** [comment] 2018-07-10 13:47
Any differences in browsers or environments?

**Comment by ryoung2512** [comment] 2018-07-10 13:48
We all tested on firefox, only difference is that Kevin and I use Macs.. not sure if that could cause anything.

**Comment by ian-james** [comment] 2018-07-10 13:50
I would check chrome too since it's a main supported browser.

Mac might cause differences.

**Comment by ryoung2512** [comment] 2018-07-10 18:33
Apparently grant was able to reproduce this error once that jamey was talking about. Kevin thinks it has to do with the ajax call not returning data in time. @ndomenic wait for the ajax call to finish before updating the pill.

**Comment by GrantDouglas** [comment] 2018-07-16 16:34
I found a fix that can be used. I made the buttons square instead of rounded to remove the buffer area around the button. It looks fine to me, but might need other peoples perspectives on it.

**Comment by GrantDouglas** [comment] 2018-07-16 17:03
I looked through the main css file and found the cause of the problem. Will make a pull request on the branch it is currently on.

**Comment by ian-james** [comment] 2018-07-16 17:10
Awesome. Thanks!

**Comment by ryoung2512** [comment] 2018-07-19 13:39
It was merged in today to development. I tested it out and the bug is no longer there. Going to go ahead and close this issue.

**Closed by ryoung2512** 2018-07-19 13:39 UTC
Labels: bug
